projects:
  app:
    schemaPath: 'src/schema.graphql'
    extensions:
      endpoints:
        default: 'https://sick-fits-prod-dbbd8cb7ec.herokuapp.com/sick-fits-prod/prod'
  prisma:
    schemaPath: 'src/generated/prisma.graphql'
    extensions:
      prisma: prisma.yml
